print('Boas vindas ao nosso MADLIB')
titulo = input('Digite o título do MADLIB: ')
adjetivo = input('Digite um adjetivo: ')
lugar = input('Digite um lugar: ')
substantivo = input('Digite um substantivo: ')
nome = input('Digite um nome: ')
nome2 = input('Digite um nome: ')
verbo = input('Digite um verbo: ')
substantivo2 = input('Digite um substantivo: ')
adjetivo2 = input('Digite um adjetivo: ')
substantivo3 = input('Digite um substantivo: ')
verbo2 = input('Digite um verbo: ')

print('Título: ' + titulo)

print('Era uma vez, em um(a) '+ adjetivo + ' ' + lugar + ', havia um(a) ' + substantivo + ' chamado(a) ' + nome  + '. Cada dia, ' + nome2 +' gostava de ' + verbo + ' com seu(sua) ' + substantivo2 + '. Um dia, ele(a) encontrou um(a) '+ adjetivo2 + ' '+ substantivo3 + ' que mudou tudo. Eles decidiram '+ verbo2 + ' juntos e viveram felizes para sempre.')